# This is a basic workflow to help you get started with Actions

name: Q1_Chuzeville_Jules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Copy TOTO.txt to Q1_archive_TOTO.txt
        run: cp TOTO.txt Q1_archive_TOTO.txt

      # Runs a set of commands using the runners shell
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Q1_archive_TOTO.txt
          git commit -m "Add Q1_archive_TOTO.txt from TOTO.txt" || echo "No changes to commit"
          git push
