# This is a basic workflow to help you get started with Actions

name: Q3_Chuzeville_Jules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Q3_archive_java.txt
        run: |
          echo "Nom et prénom : Jules Chuzeville" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q3_archive_java.txt
          echo "---------------------------------" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt
          echo "---------------------------------" >> Q3_archive_java.txt

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add Q3_archive_java.txt
          git diff --cached --quiet && echo "Aucun changement à committer" && exit 0
          git commit -m "Add Q3_archive_java.txt"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref_name }}
