# This is a basic workflow to help you get started with Actions

name: Q3_Chuzeville_Jules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
permissions:
  contents: write

concurrency:
  group: push-to-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate Q3_archive_java.txt
        run: |
          echo "Nom et prénom : Jules Chuzeville" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q3_archive_java.txt
          echo "---------------------------------" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt
          echo "---------------------------------" >> Q3_archive_java.txt

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add Q3_archive_java.txt
          git diff --cached --quiet && echo "Aucun changement à committer" && exit 0
          git commit -m "Add Q3_archive_java.txt"

      - name: Push with retry on non-fast-forward
        run: |
          set -e
          for i in 1 2 3; do
            if git push origin HEAD:${{ github.ref_name }}; then
              exit 0
            fi
            echo "Push rejeté (tentative $i). Rebase sur la dernière version distante puis retry…"
            git pull --rebase origin ${{ github.ref_name }} || true
          done
          echo "Échec: impossible de pousser après 3 tentatives." >&2
          exit 1
