# This is a basic workflow to help you get started with Actions

name: Q5_Chuzeville_Jules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: push-to-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with token)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate archive file with FR date in filename
        run: |
          DATE_STR=$(date +'%d-%m-%Y')
          FILENAME="Q5_archive_date_${DATE_STR}.txt"

          if [ ! -f Q5.java ]; then
            echo "Q5.java introuvable à la racine du dépôt." >&2
            exit 1
          fi

          echo "Nom et prénom : Jules Chuzeville" > "$FILENAME"
          echo "" >> "$FILENAME"
          echo "Contenu de Q5.java :" >> "$FILENAME"
          echo "---------------------------------" >> "$FILENAME"
          cat Q5.java >> "$FILENAME"
          echo "" >> "$FILENAME"
          echo "---------------------------------" >> "$FILENAME"

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Pull latest changes (avoid non-fast-forward)
        run: |
          git pull --rebase --autostash origin ${{ github.ref_name }} || true

      - name: Commit changes
        run: |
          git add Q5_archive_date_*.txt
          git diff --cached --quiet && echo "Aucun changement à committer" && exit 0
          git commit -m "Add Q5 archive with dated filename"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
